name: economymonitor
favicon: null
layout_spectrum: 0.11260194820351899
typography_spectrum: 0.48315250664018095
title: EM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.43104385188780725
  lightness: 0.35089679760858417
  saturation: 0.953498724848032
  rhythmicContrast: 0.24273552652448416
purpose: []
